# =========================
# Build stage
# =========================
FROM golang:1.23 AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -gcflags "all=-N -l" -o worker ./cmd/worker


# =========================
# Delve build stage
# =========================
FROM golang:1.23 AS delve-build
RUN apt-get update && apt-get install -y git make
RUN git clone https://github.com/go-delve/delve.git /dlv
WORKDIR /dlv
RUN make build  # creates ./dlv binary compatible with Go 1.23+


# =========================
# Debug runtime stage
# =========================
FROM debian:bookworm

RUN apt-get update && apt-get install -y ca-certificates

WORKDIR /app

# copy worker binary
COPY --from=build /src/worker /app/worker

# copy debug-compatible Delve
COPY --from=delve-build /dlv/dlv /usr/local/bin/dlv
RUN chmod +x /usr/local/bin/dlv

EXPOSE 40001

CMD ["dlv", "exec", "/app/worker", "--headless", "--listen=:40001", "--api-version=2", "--accept-multiclient", "--check-go-version=false", "--continue", "--"]


