openapi: 3.0.3
info:
  title: Chronosched API
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /healthz:
    get:
      summary: Health check
      responses:
        '200':
          description: Service healthy
          content:
            text/plain:
              schema:
                type: string
                example: ok
  /api/v1/namespaces:
    get:
      summary: List namespaces
      responses:
        '200':
          description: List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Namespace'
    post:
      summary: Create namespace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NamespaceCreateRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Namespace'
  /api/v1/namespace/{name}:
    parameters:
    - name: name
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Get namespace
      responses:
        '200':
          description: Namespace
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Namespace'
    put:
      summary: Rename namespace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NamespaceRenameRequest'
      responses:
        '200':
          description: Renamed
          content:
            application/json:
              schema:
                type: object
                properties:
                  old:
                    type: string
                  new:
                    type: string
    delete:
      summary: Delete namespace
      responses:
        '204':
          description: Deleted
  /api/v1/dags/{namespace_id}:
    parameters:
    - name: namespace_id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: List DAGs
      responses:
        '200':
          description: List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DAG'
    post:
      summary: Create DAGs (bulk)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DAGCreateRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
    put:
      summary: Upsert DAGs (bulk)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DAGCreateRequest'
      responses:
        '200':
          description: Upserted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
  /api/v1/dags/{namespace_id}/{id}:
    parameters:
    - name: namespace_id
      in: path
      required: true
      schema:
        type: string
    - name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
    get:
      summary: Get DAG
      responses:
        '200':
          description: DAG
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DAG'
    put:
      summary: Update DAG name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DAG'
    delete:
      summary: Delete DAG
      responses:
        '204':
          description: Deleted
  /api/v1/definitions/{namespace_id}:
    parameters:
    - name: namespace_id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: List definitions
      responses:
        '200':
          description: List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobDefinition'
    post:
      summary: Create definitions (bulk)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/JobDefinitionCreateRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
    put:
      summary: Upsert definitions (bulk)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/JobDefinitionCreateRequest'
      responses:
        '200':
          description: Upserted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
  /api/v1/definitions/{namespace_id}/{id}:
    parameters:
    - name: namespace_id
      in: path
      required: true
      schema:
        type: string
    - name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
    get:
      summary: Get definition
      responses:
        '200':
          description: Definition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDefinition'
  /api/v1/dags/{namespace_id}/{dagId}/jobs:
    parameters:
    - name: namespace_id
      in: path
      required: true
      schema:
        type: string
    - name: dagId
      in: path
      required: true
      schema:
        type: string
        format: uuid
    get:
      summary: List jobs in DAG
      responses:
        '200':
          description: List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
    post:
      summary: Create jobs (bulk)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/JobCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
    put:
      summary: Upsert jobs (bulk)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/JobCreate'
      responses:
        '200':
          description: Upserted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
  /api/v1/dags/{namespace_id}/{dagId}/jobs/{id}:
    parameters:
    - name: namespace_id
      in: path
      required: true
      schema:
        type: string
    - name: dagId
      in: path
      required: true
      schema:
        type: string
        format: uuid
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Get job by id (in DAG)
      responses:
        '200':
          description: Job
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
  /api/v1/dags/{namespace_id}/{dagId}/dependencies:
    parameters:
    - name: namespace_id
      in: path
      required: true
      schema:
        type: string
    - name: dagId
      in: path
      required: true
      schema:
        type: string
        format: uuid
    get:
      summary: List dependencies
      responses:
        '200':
          description: List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dependency'
    post:
      summary: Create dependencies (bulk)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DependencyCreateRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
    put:
      summary: Upsert dependencies (bulk)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DependencyCreateRequest'
      responses:
        '200':
          description: Upserted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
  /api/v1/jobs/{namespace_id}/{jobId}/complete:
    parameters:
    - name: namespace_id
      in: path
      required: true
      schema:
        type: string
    - name: jobId
      in: path
      required: true
      schema:
        type: integer
    post:
      summary: Mark job complete
      responses:
        '204':
          description: Completed
  /api/v1/jobs/{namespace_id}/{jobId}/fail:
    parameters:
    - name: namespace_id
      in: path
      required: true
      schema:
        type: string
    - name: jobId
      in: path
      required: true
      schema:
        type: integer
    post:
      summary: Mark job failed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FailRequest'
      responses:
        '204':
          description: Failed set
  /api/v1/admin/check/global-cycles:
    get:
      summary: Check global cycles across all DAGs
      responses:
        '200':
          description: Cycle check
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CycleCheckResponse'
components:
  schemas:
    NamespaceCreateRequest:
      type: object
      required:
      - name
      properties:
        name:
          type: string
          example: demo
    NamespaceRenameRequest:
      type: object
      required:
      - new_name
      properties:
        new_name:
          type: string
          example: prod
    Namespace:
      type: object
      properties:
        namespace_id:
          type: string
          format: uuid
          example: 4e8b2f8c-74a1-4c3e-97de-4f43eb3a0c9b
        name:
          type: string
          example: demo
    DAGCreateRequest:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: string
          format: uuid
          example: 2fd2fef5-3a9d-44e1-b5a2-34da5e58aeb3
        name:
          type: string
          example: nightly_etl
    DAG:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 2fd2fef5-3a9d-44e1-b5a2-34da5e58aeb3
        namespace:
          type: string
          example: demo
        name:
          type: string
          example: nightly_etl
        created_at:
          type: string
          format: date-time
          example: '2025-11-11T03:40:05Z'
    JobDefinitionCreateRequest:
      type: object
      required:
      - name
      - version
      - kind
      - payload_template
      properties:
        name:
          type: string
          example: ParentJob
        version:
          type: integer
          example: 1
        kind:
          type: string
          enum:
          - cmd
          - http
          - binary
          example: cmd
        payload_template:
          type: object
          example:
            cmd: echo hello
        cron_spec:
          type: string
          example: '@every 5s'
        delay_interval:
          type: string
          example: 5 minutes
    JobDefinition:
      type: object
      properties:
        def_id:
          type: string
          format: uuid
          example: c413e1f9-9127-47c5-bb77-f98aa1b3ec50
        namespace:
          type: string
          example: demo
        name:
          type: string
          example: ParentJob
        version:
          type: integer
          example: 1
        kind:
          type: string
          example: cmd
        payload_template:
          type: object
          example:
            cmd: echo hello
        created_at:
          type: string
          format: date-time
          example: '2025-11-11T03:40:05Z'
    JobCreate:
      type: object
      required:
      - def_id
      properties:
        def_id:
          type: string
          format: uuid
          example: c413e1f9-9127-47c5-bb77-f98aa1b3ec50
        payload:
          type: string
          example: '{}'
        priority:
          type: integer
          example: 0
        due_at:
          type: string
          format: date-time
          example: '2025-11-11T04:10:00Z'
    Job:
      type: object
      properties:
        id:
          type: integer
          example: 101
        dag_id:
          type: string
          format: uuid
          example: 2fd2fef5-3a9d-44e1-b5a2-34da5e58aeb3
        def_id:
          type: string
          format: uuid
          example: c413e1f9-9127-47c5-bb77-f98aa1b3ec50
        status:
          type: string
          enum:
          - waiting
          - queued
          - running
          - succeeded
          - failed
          - cancelled
          example: queued
        kind:
          type: string
          example: cmd
        payload_json:
          type: object
          example:
            cmd: echo hello
        due_at:
          type: string
          format: date-time
          example: '2025-11-11T04:10:00Z'
    DependencyCreateRequest:
      type: object
      required:
      - ParentID
      - ChildID
      properties:
        ParentID:
          type: integer
          example: 101
        ChildID:
          type: integer
          example: 102
    Dependency:
      type: object
      properties:
        parent_job_id:
          type: integer
          example: 101
        child_job_id:
          type: integer
          example: 102
    FailRequest:
      type: object
      required:
      - error
      properties:
        error:
          type: string
          example: exit code 1
    CountResponse:
      type: object
      properties:
        count:
          type: integer
          example: 2
    CycleCheckResponse:
      type: object
      properties:
        count:
          type: integer
          example: 0
        results:
          type: array
          items:
            type: object
            properties:
              dag_id:
                type: string
                format: uuid
              cycles:
                type: array
                items:
                  type: array
                  items:
                    type: string
